name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y --no-install-recommends \
              python3-pip build-essential git python3-dev libssl-dev \
              libffi-dev zlib1g-dev automake autoconf libtool pkg-config python3-setuptools \
          || sudo apt-get install -y --fix-broken

      - name: Install Buildozer via pip
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython

      - name: Initialize Buildozer (to create .buildozer directory)
        run: |
          buildozer init || exit 2

      - name: Set permissions on .buildozer directory (after initialization)
        run: |
          sudo chmod -R 777 .buildozer

      - name: Build with Buildozer (Verbose)
        run: |
          buildozer android debug --verbose || exit 2

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
