name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies including buildozer, Android SDK, NDK
      - name: Install buildozer and dependencies
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y --no-install-recommends \
              python3-pip build-essential git python3-dev libssl-dev \
              libffi-dev zlib1g-dev automake autoconf libtool pkg-config python3-setuptools
          pip install --upgrade pip
          pip install buildozer cython
        
      - name: Install Android SDK and NDK
        run: |
          sudo apt-get install -y android-sdk ndk
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools/latest/bin
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30"

      - name: Build with Buildozer
        run: buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk

